import matplotlib.pyplot as plt

# Read in output generated by parallelization and extract computation times and 
# number of cores
with open('q2.out', 'r') as f:
    lines = f.readlines()
    computation_times = [] # Initialize empty list to store computation times
    cores = [] # Initialize empty list to store number of cores
    for line in lines:
        columns = line.split()
        computation_times.append(float(columns[5]))
        cores.append(int(columns[8]))

# Create the plot where x is number of cores and y is computation times
plt.plot(cores, computation_times)

# Set the x-axis ticks to show all integers from 1 to 20
plt.xticks(range(1, 21))

# Add axis labels and a title
plt.xlabel('Number of Cores')
plt.ylabel('Computation Time (seconds)')
plt.title('Computation Time vs. Number of Cores for 1.000 simulations')

# Display the plot
plt.show()